# Generated by Django 5.2.15 on 2026-06-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('5min', '5 daqiqalik (test)'), ('3d', '3 kunlik'), ('1m', '1 oylik'), ('3m', '3 oylik'), ('6m', '6 oylik'), ('1y', '1 yillik')], help_text="Tanlangan obuna muddati. O'zgartirilganda tugash vaqti shu paytdan qayta hisoblanadi.", max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
