# Generated by Django 5.2.15 on 2026-06-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('3d', '3 kunlik'), ('1m', '1 oylik'), ('3m', '3 oylik'), ('6m', '6 oylik'), ('1y', '1 yillik')], help_text="Tanlangan obuna muddati. O'zgartirilganda tugash vaqti shu paytdan qayta hisoblanadi.", max_length=8),
        ),
    ]
