# Generated by Django 5.2.15 on 2026-06-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_companies',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 ta kompaniya'), (3, '3 ta kompaniya')], default=1, help_text='Bu foydalanuvchi maksimal nechta kompaniya (profil) ocha oladi.', verbose_name='Kompaniyalar limiti'),
        ),
    ]
