# Generated by Django 5.2.15 on 2026-06-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='article',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='cost',
            name='brand',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
