# Generated by Django 5.2.15 on 2026-06-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_cost_article_cost_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfpurchase',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='selfpurchase',
            name='logistics',
            field=models.FloatField(default=0),
        ),
    ]
